// vue/shoppinglistfront/src/components/ShoppingForm.vue
<template>
	<div>
		<label>Item type:</label>
		<input type="text" v-model="item.type"/>
		<br/>
		<label>Price:</label>
		<input type="number" v-model="item.price"/>
		<br/>
		<label>Count:</label>
		<input type="number" v-model="item.count"/>
		<br/>
		<button v-on:click="addToList()">Add</button>
	</div>
</template>

<script>
export default {
	name:"ShoppingForm",
	data: function() {
		return {
			item: {
				type:"",
				price:0,
				count:0,
				id:0			
			}
		
		}
	},
	methods: {
		addToList:function() {
			this.$emit("add-to-list",this.item);
			this.item = {
				type:"",
				price:0,
				count:0,
				id:0			
			}
		}	
	}

}

</script>

// angular/services/src/app/components/shoppingform/shoppingform.component.ts
import {Component} from '@angular/core';
import {ShoppingService} from '../../services/shoppingservice.service';
import {ShoppingItem} from '../../models/shoppingitem.model';

@Component({
	selector:"shoppingform",
	templateUrl:"./shoppingform.component.html"
})
export class ShoppingForm {
	
	shoppingitem:ShoppingItem;
	
	constructor(private _service:ShoppingService) {
		this.shoppingitem = new ShoppingItem("",0,0);
	}
	
	addToList() {
		this._service.addToList(this.shoppingitem);
		this.shoppingitem = new ShoppingItem("",0,0);
	}
}

<div>
	<form (ngSubmit)="addToList()" #shoppingForm="ngForm">
		<label for="type">Item type</label>
		<input name="type" 
		       type="text" 
			   required 
			   [(ngModel)]="shoppingitem.type"/>
		<br/>
		<label for="price">Price</label>
		<input name="price" 
			   type="number" 
			   required 
			   minimum="0.0"
			   step="0.01"
			   [(ngModel)]="shoppingitem.price"/>
		<br/>
		<label for="count">Count</label>
		<input name="count" 
			   type="number" 
			   required 
			   minimum="0"
			   [(ngModel)]="shoppingitem.count"/>
		<br/>
		<input type="submit" value="Submit"/>
	</form>
</div>
