// vue/shoppinglistfront/src/components/ShoppingList.vue
<template>
	<div>
		<table>
			<thead>
				<tr>
					<th>Type</th>
					<th>Price</th>
					<th>Count</th>
					<th>Remove</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="item in list" :key="item.id">
					<td>{{item.type}}</td>
					<td>{{item.price}}</td>
					<td>{{item.count}}</td>
					<td><button v-on:click="remove(item.id)">Remove</button></td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<script>
export default {
	name:"ShoppingList",
	props:["list"],
	methods: {
		remove:function(id) {
			this.$emit("remove-item",id);
		}
	}
}	

</script>

// angular/services/src/app/components/shoppinglist/shoppinglist.component.ts
import {Component} from '@angular/core';
import {ShoppingService} from '../../services/shoppingservice.service';
import {ShoppingItem} from '../../models/shoppingitem.model';

@Component({
	selector:"shoppinglist",
	templateUrl:"./shoppinglist.component.html"
})
export class ShoppingList {
	
	shoppingitems:ShoppingItem[] = [];
	
	constructor(private _service:ShoppingService){

	}
	
	getList() {
		this.shoppingitems = this._service.getList();
	}
	
	remove(index) {
		this._service.remove(index);
		this.getList();
	}
}
<div>
	<button (click)="getList()">Get List</button>
	<table>
		<thead>
			<tr>
				<th>Type</th>
				<th>Count</th>
				<th>Price</th>
				<th>Remove</th>
			</tr>
		</thead>
		<tbody>
			<tr *ngFor="let item of shoppingitems; let idx = index">
				<td>{{item.type}}</td>
				<td>{{item.count}}</td>
				<td>{{item.price}}</td>
				<td><button (click)="remove(idx)">Remove</button></td>
			</tr>
		</tbody>
	</table>
</div>
