// react/listsandforms/src/ShoppingList.js
import React from 'react';
import {Table, Button} from 'semantic-ui-react';

export default class ShoppingList extends React.Component {

	
	render() {
		let listItems = this.props.list.map((item) => 
			<Table.Row key={item.id}>
				<Table.Cell>{item.type}</Table.Cell>
				<Table.Cell>{item.count}</Table.Cell>
				<Table.Cell>{item.price}</Table.Cell>
			</Table.Row>
		)
		
		return (
			<Table celled>
				<Table.Header>
					<Table.Row>
						<Table.HeaderCell>Type</Table.HeaderCell>
						<Table.HeaderCell>Count</Table.HeaderCell>
						<Table.HeaderCell>Price</Table.HeaderCell>
					</Table.Row>
				</Table.Header>
				<Table.Body>
				{listItems}
				</Table.Body>
			</Table>
		)
	}

}

// vue/shoppinglistfront/src/components/ShoppingList.vue
<template>
	<div>
		<table>
			<thead>
				<tr>
					<th>Type</th>
					<th>Price</th>
					<th>Count</th>
					<th>Remove</th>
				</tr>
			</thead>
			<tbody>
				<tr v-for="item in list" :key="item.id">
					<td>{{item.type}}</td>
					<td>{{item.price}}</td>
					<td>{{item.count}}</td>
					<td><button v-on:click="remove(item.id)">Remove</button></td>
				</tr>
			</tbody>
		</table>
	</div>
</template>

<script>
export default {
	name:"ShoppingList",
	props:["list"],
	methods: {
		remove:function(id) {
			this.$emit("remove-item",id);
		}
	}
}	

</script>
